#!/usr/bin/bash
mkdir -p ~/.vim
mkdir -p ~/.vim/autoload

mkdir -p ~/.config/nvim
mkdir -p ~/.config/nvim/autoload

mv -s ./plug.vim ~/.vim/autoload/plug.vim
mv -s ./plug.vim ~/.config/nvim/autoload/plug.vim

cp ./vimrc ~/.vimrc
ln -s ~/.vimrc ~/.config/nvim/init.vim
